config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {:sessions => "users/sessions", :registrations => "users/registrations"}
  resources :users
  resources :aboutus
  resources :products
  resources :customers
  resources :main_products
  resources :fronts

   get 'home' => 'fronts#home'
   get 'our_products' => 'fronts#our_products'
   get 'about' => 'fronts#about'
   get 'contact' => 'fronts#contact'
   get 'our_new_product' => 'fronts#our_new_product'
   
  

  root 'fronts#home'

end

app/models/aboutu.rb
class Aboutu < ActiveRecord::Base
end

app/controllers/aboutus_controller.rb
class AboutusController < ApplicationController
  before_action :set_aboutu, only: [:show, :edit, :update, :destroy]
    layout "backend"
  before_action :authenticate_user!
  # GET /aboutus
  # GET /aboutus.json
  def index
    @aboutus = Aboutu.all
  end

  # GET /aboutus/1
  # GET /aboutus/1.json
  def show
  end

  # GET /aboutus/new
  def new
    @aboutu = Aboutu.new
  end

  # GET /aboutus/1/edit
  def edit
  end

  # POST /aboutus
  # POST /aboutus.json
  def create
    @aboutu = Aboutu.new(aboutu_params)

    respond_to do |format|
      if @aboutu.save
        format.html { redirect_to @aboutu, notice: 'Aboutu was successfully created.' }
        format.json { render :show, status: :created, location: @aboutu }
      else
        format.html { render :new }
        format.json { render json: @aboutu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aboutus/1
  # PATCH/PUT /aboutus/1.json
  def update
    respond_to do |format|
      if @aboutu.update(aboutu_params)
        format.html { redirect_to @aboutu, notice: 'Aboutu was successfully updated.' }
        format.json { render :show, status: :ok, location: @aboutu }
      else
        format.html { render :edit }
        format.json { render json: @aboutu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aboutus/1
  # DELETE /aboutus/1.json
  def destroy
    @aboutu.destroy
    respond_to do |format|
      format.html { redirect_to aboutus_url, notice: 'Aboutu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aboutu
      @aboutu = Aboutu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aboutu_params
      params.require(:aboutu).permit(:about)
    end
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/views/aboutus/_form.html.erb
<div class="container">

<%= form_for(@aboutu) do |f| %>
  <% if @aboutu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aboutu.errors.count, "error") %> prohibited this aboutu from being saved:</h2>

      <ul>
      <% @aboutu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :about %><br>
    <%= f.text_area :about, :class=>"form-control", :rows => 14 %>
  </div>
  <div class="actions">
    <%= f.submit "save" %>
  </div>
<% end %>


</div>

app/views/aboutus/edit.html.erb
<h1>About us</h1>

<%= render 'form' %>

app/views/aboutus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Aboutus</h1>

<table>
  <thead>
    <tr>
      <th>About</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aboutus.each do |aboutu| %>
      <tr>
        <td><%= aboutu.about %></td>
        <td><%= link_to 'Show', aboutu %></td>
        <td><%= link_to 'Edit', edit_aboutu_path(aboutu) %></td>
        <td><%= link_to 'Destroy', aboutu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aboutu', new_aboutu_path %>

app/views/aboutus/new.html.erb
<h1>New Aboutu</h1>

<%= render 'form' %>

app/views/aboutus/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
<p>
  <strong>About:</strong>
  <%= @aboutu.about %>
</p>

<%= link_to 'Edit', edit_aboutu_path(@aboutu) %> |
<%= link_to 'Back', aboutus_path %>
</div>