config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {:sessions => "users/sessions", :registrations => "users/registrations"}
  resources :users
  resources :aboutus
  resources :products
  resources :customers
  resources :main_products
  resources :fronts

   get 'home' => 'fronts#home'
   get 'our_products' => 'fronts#our_products'
   get 'about' => 'fronts#about'
   get 'contact' => 'fronts#contact'
   get 'our_new_product' => 'fronts#our_new_product'
   
  

  root 'fronts#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>

<title>LUCKY BAG & SWALLOW</title>
<link rel="shortcut icon" href="<%= asset_path 'm.png'%>">

<!-- For-Mobile-Apps -->

	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="Lucky Bags a Responsive Web Template, Bootstrap Web Templates, Flat Web Templates, Android Compatible Web Template, Smartphone Compatible Web Template, Free Webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola Web Design" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

	 <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

	<%= javascript_include_tag 'modernizr.js' %>
	<%= javascript_include_tag 'modernizr-2.6.2.min.js' %>
	<%= javascript_include_tag 'jquery.min.js' %>
	<%= javascript_include_tag 'jquery.mobile.customized.min.js' %>
	<%= javascript_include_tag 'jquery.easing.1.3.js' %>
	<%= javascript_include_tag 'camera.js' %>
	<%= javascript_include_tag 'velocity.min.js' %>
	<%= javascript_include_tag 'main.nav.js' %>
	<%= javascript_include_tag 'cbpFWTabs.js' %>
	<%= javascript_include_tag 'numscroller-1.0.js' %>
	<%= javascript_include_tag 'jquery.inview.min.js' %>
	<%= javascript_include_tag 'wow.min.js' %>
	<%= javascript_include_tag 'mousescroll.js' %>
	<%= javascript_include_tag 'main.js' %>
	<%= javascript_include_tag 'move-top.js' %>
	<%= javascript_include_tag 'easing.js' %>
	<%= javascript_include_tag 'bootstrap.min.js' %>


     <%= csrf_meta_tags %>



</head>

<body>

	<!-- Header -->
	<div class="header" id="home">



			<nav class="navbar navbar-default" style="background-color: #34BBB1;">
			  <div class="container-fluid">
			    <div class="navbar-header">
			     	<%= link_to 'Home', root_path, :class=>"btn btn-default navbar-btn", :id=>"nav_btn" %>
					<%= link_to 'Product', our_products_path, :class=>"btn btn-default navbar-btn", :id=>"nav_btn" %>
				    <%= link_to 'About us', about_path, :class=>"btn btn-default navbar-btn", :id=>"nav_btn" %>
					<%= link_to 'Contact', contact_path, :class=>"btn btn-default navbar-btn", :id=>"nav_btn" %>

					<p class="navbar-text navbar-left">
					<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>Email : 
					<a href="mailto:info@luckybagmyanmar.com" style="color:white;font-size:11px;">
					info@luckybagmyanmar.com</a>

					</p>
					<p class="navbar-text navbar-left">
					<span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>Phone : <a href="#" style="color:white;font-size:11px;">+95 (09)527400</a>
					</p>
				

			    </div>
			  </div>
			</nav>

		<!-- Top-Bar -->
		
		<!-- //Top-Bar -->

		<!-- Bottom-Bar -->
		<div class="bottom-bar">
			<!-- Logo -->
			<div class="logo">
				<%= image_tag "lucky_bag_logo.png", :id=>"my_logo", :alt=>"Lucky Bags" %>
			</div>
			<!-- //Logo -->

			<!-- Social-Icons -->
			<div class="social">
				<ul>
					<li><a href="#" class="facebook" title="Go to Our Facebook Page"></a></li>
					<li><a href="#" class="twitter" title="Go to Our Twitter Account"></a></li>
				</ul>
			</div>
			<!-- //Social-Icons -->
			<div class="clearfix"></div>
		</div>
		<!-- //Bottom-Bar -->

		<!-- Navigation -->
		<nav>
			<ul class="cd-primary-nav">
				<li><%= link_to 'Home', root_path %></li>
			    <li><%= link_to 'Product', our_products_path %></li>
				<li><%= link_to 'About us', about_path %></li>
				<li><%= link_to 'Contact', contact_path %></li>
			</ul>
		</nav>

		<div class="cd-overlay-nav">
			<span></span>
		</div>

		<div class="cd-overlay-content">
			<span></span>
		</div>

	
		<!-- //Navigation -->

		<!-- Slider -->
	
	<!-- //Header -->

	<%= yield %>

	<!-- Footer -->
	<div class="footer">
		
		<div class="footer-grid-2 contact-us">
			<div class="container">
				<h4>Contact us</h4>
				<div class="col-md-6 col-sm-6 contact-us-grid">
					<p>Office: No.20, East Horse Race Course Street,</p>
					<p>Tamwe Township, Yangon, Myanmar.</p>
					<p>Tel: 544124, 557800, 09-73073114, 09-73078500</p>
				</div>
				<div class="col-md-6 col-sm-6 contact-us-grid">
					<p>Factory: No.72, Thu Khi Tar Street,</p>
					<p>Dagon Seikkan Industrial Zone(2) </p>
					<p>09-788022612, 09-788022603, 09-73078455</p>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	
		<div class="footer-grid-4 copyright">
			<p>&copy; 2016 Lucky Bag & Swallow. All Rights Reserved | Produce by <a href="http://hnttechs.com/"> H&Ttechs </a></p>
		</div>

	</div>
	<!-- //Footer -->


	<script>
		jQuery(function(){
			jQuery('#camera_wrap_2').camera({
				loader: 'bar',
				pagination: false,
				thumbnails: false
			});
		});
	</script>

	<script>
		(function() {
			[].slice.call( document.querySelectorAll( '.tabs' ) ).forEach( function( el ) {
				new CBPFWTabs( el );
			});
		})();
	</script>

	<script type="text/javascript">
			jQuery(document).ready(function($) {
				$(".scroll, .navbar li a, .footer li a").click(function(event){
					$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
				});
			});
	</script>
	<!-- //Smooth-Scrolling-JavaScript -->

	<!-- Slide-To-Top JavaScript (No-Need-To-Change) -->
	<script type="text/javascript">
		$(document).ready(function() {
			var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 100,
				easingType: 'linear'
			};
			$().UItoTop({ easingType: 'easeOutQuart' });
		});
	</script>
	<a href="#home" id="toTop" class="scroll" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
	<!-- //Slide-To-Top JavaScript -->

<!-- //Custom-JavaScript-File-Links -->

</body>

</html>

app/views/layouts/backend.html.erb
<!DOCTYPE html>
<html>

<head>

	<title>LUCKY BAG & SWALLOW: BACKEND SYSTEM</title>
	<link rel="shortcut icon" href="<%= asset_path 'm.png'%>">
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
     <%= csrf_meta_tags %>



</head>

<body>

  <% if user_signed_in? %>

        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">LUKCY BAGS</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
               

              <!-- about us -->
              	 <li ><%= link_to 'About Us', edit_aboutu_path(1) %></li>

                <!-- customers -->
                 <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">CUSTOMERS <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'Add New Customers', new_customer_path %></li>
                    <li><%= link_to 'Edit Existing Customers', customers_path %></li>
                  </ul>
                </li>

                <!-- main products -->
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> MAIN PRODUCTS <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'Add New Main Products', new_main_product_path %></li>
                    <li><%= link_to 'Edit Existing Products', main_products_path %></li>
                  </ul>
                </li>

                <!-- products -->
                 <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">PRODUCTS <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                        <li><%= link_to 'Add New Main Products', new_product_path %></li>
                        <li><%= link_to 'Edit Existing Products', products_path %></li>
                  </ul>
                </li>

              </ul>
            
              <ul class="nav navbar-nav navbar-right">
                <li>  <%= link_to "Log out", destroy_user_session_path, :method => :delete  %></li>
              </ul>



            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>

    <% else %>


    <% end %>


	<%= yield %>

	

</body>

</html>